name: terraform

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  fmt_validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install terraform (if missing)
        shell: bash
        run: |
          set -euo pipefail
          if command -v terraform >/dev/null 2>&1; then
            terraform version
            exit 0
          fi
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -fsSL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.14.3/terraform_1.14.3_linux_amd64.zip
          sudo unzip -o /tmp/terraform.zip -d /usr/local/bin
          terraform version

      - name: Terraform fmt
        shell: bash
        run: |
          set -euo pipefail
          terraform fmt -check -recursive

      - name: Terraform init (backend/local)
        shell: bash
        run: |
          set -euo pipefail
          terraform init -input=false

      - name: Terraform validate
        shell: bash
        run: |
          set -euo pipefail
          terraform validate

  plan_main:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [fmt_validate]
    env:
      TF_IN_AUTOMATION: "1"
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      TF_VAR_token_reviewer_jwt: ${{ secrets.TF_VAR_token_reviewer_jwt }}
      TF_VAR_kubernetes_ca_cert_pem: ${{ secrets.TF_VAR_kubernetes_ca_cert_pem }}
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install terraform (if missing)
        shell: bash
        run: |
          set -euo pipefail
          if command -v terraform >/dev/null 2>&1; then
            terraform version
            exit 0
          fi
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -fsSL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.14.3/terraform_1.14.3_linux_amd64.zip
          sudo unzip -o /tmp/terraform.zip -d /usr/local/bin
          terraform version

      - name: Guard: required secrets
        shell: bash
        run: |
          set -euo pipefail
          : "${VAULT_ADDR:?Set Forgejo secret VAULT_ADDR (e.g. http://platform-vault.vault.svc:8200)}"
          : "${VAULT_TOKEN:?Set Forgejo secret VAULT_TOKEN (scoped token; avoid long-lived root)}"
          : "${TF_VAR_token_reviewer_jwt:?Set Forgejo secret TF_VAR_token_reviewer_jwt}"
          : "${TF_VAR_kubernetes_ca_cert_pem:?Set Forgejo secret TF_VAR_kubernetes_ca_cert_pem}"

      - name: Terraform init
        shell: bash
        run: |
          set -euo pipefail
          terraform init -input=false

      - name: Import existing resources (idempotent)
        shell: bash
        run: |
          set -euo pipefail
          ./scripts/import-existing.sh

      - name: Terraform plan
        shell: bash
        run: |
          set -euo pipefail
          terraform plan -input=false -no-color

